### PR TITLE
Remove root module

### PR DESCRIPTION
**Pull request by dmathieu**
This is an alternative solution for the tidy issue in https://github.com/open-telemetry/opentelemetry-proto-go/pull/193

Related: https://github.com/open-telemetry/opentelemetry-proto-go/pull/211

### CODE REVIEW

**Review by pellared — COMMENTED** [review]
`versions.yaml` needs to be updated. Otherwise, the release will fail.
It would be good to run `$(MULTIMOD) verify` in CI.

**Comment by pellared** [comment]
I just realized that without the root module the `v*` tags will not be created and pushed by the release automation. We would need to update the `push-tags` Make target to publish them...

**Comment by pellared** [comment]
I just want to additionally mention that IMO this it not a blocker for:
- https://github.com/open-telemetry/opentelemetry-proto-go/pull/193

**Comment by dmathieu** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-proto-go/pull/211

**Pull request closed without merging**
