### PR TITLE
Release v1.5.0

### PR DESCRIPTION
**Pull request by florianl**
Release of the [v1.5.0][otlp] version of the OTLP.

[otlp]: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v1.5.0

### CODE REVIEW

**Review by pellared — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by MrAlias** [comment]
I think we need to decide on https://github.com/open-telemetry/opentelemetry-proto-go/pull/224 prior to this release.

**Comment by codeboten** [comment]
> I think we need to decide on #224 prior to this release.

I would appreciate it being included as the minimum go versioning is currently preventing me from updating otel-go dependencies in the collector

**Review by XSAM — APPROVED** [review]
https://github.com/open-telemetry/opentelemetry-proto-go/pull/224 has been merged.

**Comment by MrAlias** [comment]
We need to address the open security issue before merging: https://github.com/open-telemetry/opentelemetry-proto-go/pull/230

**Review by MikeGoldsmith — APPROVED** [review]

**Pull request merged**
