### PR TITLE
Release v0.16.0

### PR DESCRIPTION
**Pull request by tigrannajaryan**
- Release of the v0.16.0 version of the OTLP.
- Executed `make sync VERSION=v0.16.0`.

### CODE REVIEW

**Review by MrAlias — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@MrAlias the release procedure says to do `make verify`, but there is no such target. Should it be `make verify-versions`?

**Comment by tigrannajaryan** [comment]
I wasn't sure if I need to update `versions.yaml` in this PR or need to do it in a separate PR.

**Comment by MrAlias** [comment]
> @MrAlias the release procedure says to do `make verify`, but there is no such target. Should it be `make verify-versions`?

Ah, yeah, it should be `make verify-versions`.

> I wasn't sure if I need to update `versions.yaml` in this PR or need to do it in a separate PR.

Yeah, I missed that. We should include a version bump in `versions.yaml` with this PR.

**Comment by tigrannajaryan** [comment]
versions.yaml updated.

**Comment by tigrannajaryan** [comment]
@MrAlias PTAL.

**Review by MrAlias — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@MrAlias I am trying to run the next steps in the release procedure. I tried:
```
make add-tags MODSET=all
```

but it complains:
```
MODSET unset: set to taget module set from versions.yaml
```

What am I doing wrong?

(It may be easier for you to do the release, if you prefer that instead of teaching me how to do it).

**Comment by MrAlias** [comment]
Sorry about the delay. I've pushed tags for this release and made this: https://github.com/open-telemetry/opentelemetry-proto-go/releases/tag/v0.16.0

Should be good to go.

I'll touch base with you in chat about the failure. I would like to not have you blocked from making releases in the future!

**Pull request merged**
