### PR TITLE
Add slim Go module without gRPC dependencies

### PR DESCRIPTION
**Pull request by pellared**
Fixes https://github.com/open-telemetry/opentelemetry-proto-go/issues/100

Towards https://github.com/open-telemetry/opentelemetry-go/issues/2579

Add `go.opentelemetry.io/proto/slim/otlp` Go module that does not generate gRPC code.

Thanks to it codebase which only sends protobuf over HTTP can import `go.opentelemetry.io/proto/slim/otlp` that will not depend on `google.golang.org/grpc`.

The plan is to publish a `v1.2.0-rc.1` release  once this PR is merged. We prefer to release `v1.2.0` when `v1.2.0` of https://github.com/open-telemetry/opentelemetry-proto is released (to have version parity).

Tested with https://github.com/open-telemetry/opentelemetry-go/pull/5031

### CODE REVIEW

**Comment by pellared** [comment]
Postponing (changing to draft as I imagine it may be helpful).

**Review by MrAlias — APPROVED** [review]

**Comment by pellared** [comment]
> Would `go.opentelemetry.io/proto/slim/otlp` better communicate the smaller dependency nature of the package?

I like the name as it shows that it has also "has less abstractions" (offers less types, functionality). I will update the PR. Marking as draft before I rename.

**Comment by pellared** [comment]
PTAL @open-telemetry/collector-maintainers. Just to double-check. AFAIK this codebase is not used by OTel Collector, right? I see that you are generating the code from proto files on your own in https://github.com/open-telemetry/opentelemetry-collector/blob/main/Makefile.

**Review by MrAlias — APPROVED** [review]

**Comment by pellared** [comment]
@open-telemetry/go-approvers Bump. I also double-checked this PR here: Tested on https://github.com/open-telemetry/opentelemetry-go/pull/5031

**Review by MadVikingGod — APPROVED** [review]

**Pull request merged**
